let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Native dress",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "image/regina1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Slay beauty",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "image/regina11.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Lady G 001",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "image/regina12.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Casual",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "image/regina13.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Floral dress",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "image/regina4.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Classic 001",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "image/regina5.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "stripe black two piece",
    price: 450,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "image/regina6.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "longsleeve shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "image/regina7.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "denim shirt",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "image/regina8.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "bold black gean",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "image/regina9.jpg",
  },
  {
    id: "oiopijmjkhuihbn",
    name: "abaya",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "image/regina16.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "basic",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "image/regina15.jpg",
  },
  
];